spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: emergency-notification-agent
      topic: emergency-data-collector
    producer:
      group-id: emergency-notification-agent
      topic: notification-channel
  datasource:
    url: jdbc:mysql://mysql:3306/sportser
    username: toto
    password: toto

server:
  port: 8800

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka


