server:
  port: 8800

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sportser
    username: toto
    password: toto
  kafka:
    bootstrap-servers: kafka:9092
    topic-produce: notification-channel
    topic-consume: emergency-data-collector
    consumer:
      group-id: emergency-notification-agent
      properties:
        spring.json.trusted.packages: "*"

    producer:
      group-id: emergency-notification-agent
      properties:
        spring.json.trusted.packages: "*"

