spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: hr-data
      topic: hr-data-collector
    producer:
      group-id: emergency-data
      topic: emergency-data-collector
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: sportser
      username: toto
      password: password

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka

address:
  user-profile: user-profile

