eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: sportser
      username: toto
      password: password
  kafka:
    bootstrap-servers: kafka:9092
    topic-emergency: emergency-data-collector
    topic-consume: hr-data-collector
    consumer:
      group-id: emergency-service
      properties:
        spring.json.trusted.packages: "*"

    producer:
      group-id: emergency-service
      properties:
        spring.json.trusted.packages: "*"


address:
  user-profile: user-profile

