eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sportser
    username: toto
    password: toto
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
