spring:
  kafka:
      bootstrap-servers: kafka:9092
      consumer:
        group-id: hr-data
        topic: hr-data-collector

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka