version: '3.8'
services:
  zookeeper:
    image: zookeeper:3.7.0
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
    networks:
      - kafka-network
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "zkServer.sh", "status", "/conf/zoo.cfg"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000
    volumes:
      - kafka-data:/bitnami/kafka/data
    networks:
      - kafka-network
    ports:
      - "9092:9092"

networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper-data:
  zookeeper-datalog:
  kafka-data:

