eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka


heart-rate-sensor-data-collector:
  ribbon:
    listOfServers: http://data-collector:8081/

notification-channel-manager:
  ribbon:
    listOfServers: http://notification-manager:9084/
