eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-channel-group
      auto-offset-reset: earliest
      topic: notification-channel


redis:
  host: localhost
  port: 6379