spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-channel-group
      topic: notification-channel

eureka:
  client:
    serviceUrl:
      defaultZone: http://server-discovery:8761/eureka

redis:
  host: cache-redis
  port: 6379